/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class BotEngine {
  constructor(token?: string | undefined | null)
  login(token: string | undefined | null, callback: ((err: Error | null, arg: string) => void)): void
}

export declare class GatewayClient {
  token: string
  constructor()
  connect(callback: ((err: Error | null, arg: string) => void)): void
}
