import type { CodegenResult, RouteEntry } from '@astris/types'

export function generateRoutesRegistry(routes: RouteEntry[]): CodegenResult {
  const warnings: string[] = []
  const sorted = [...routes].sort((a, b) => a.path.localeCompare(b.path))

  const imports = [
    '// Auto-generated by the Bun Framework - DO NOT EDIT',
    '// Execute: bun run build to regenerate',
    '',
  ]

  const interfaceDefinition = `
export interface RouteEntry {
  pageFile?: string
  apiFile?: string
  params: string[]
}
`

  const routeEntries: string[] = []

  for (const route of sorted) {
    const entry = {
      pageFile: route.pageFile,
      apiFile: route.apiFile,
      params: route.params,
    }

    routeEntries.push(
      ` ${JSON.stringify(route.path)}: ${JSON.stringify(entry, null, 4).split('\n').join('\n')}`
    )
  }

  const content = `${imports.join('\n')} ${interfaceDefinition}
  
  export const routes: Record<string, RouteEntry> = {
  ${routeEntries.join('\n')}
  }

  export type RouteName = keyof typeof routes
  `

  return { content, warnings }
}

export function generateApiClient(_routes: RouteEntry[]): CodegenResult {
  const imports = [
    '// Automatically generated by the Bun Framework - DO NOT EDIT',
    '// Types extracted from route.ts files',
    '',
  ]

  const clientCode = `
  export const apiClient = {
    // TODO: Implement client generation using extracted types.
  }
  `

  return {
    content: `${imports.join('\n')}${clientCode}`,
    warnings: [],
  }
}
